# language: node_js
# node_js: "8"
# branches:
#   only:
#   - master
# cache:
#   directories:
#     - node_modules
# before_install:
#   - mysql -e 'CREATE DATABASE testdb;'

language: node_js
node_js:
  - "6"

script:
  - npm run lint
